name: Deploy
on:
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Name
        run: echo TAG=`date +${{ github.ref_name }}-%Y.%m.%d-%H.%M.%S` >> $GITHUB_ENV
      - name: Release
        uses: ./.github/actions/release
        with:
          tag: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
